# Generated by Django 3.1.4 on 2020-12-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201212_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='day one tests', max_length=255),
            preserve_default=False,
        ),
    ]
