# Generated by Django 3.1.4 on 2020-12-15 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201215_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default='timezone.now', max_length=255),
            preserve_default=False,
        ),
    ]
