# Generated by Django 3.1.4 on 2020-12-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201217_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='no department provided', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default='no team provided', max_length=255),
        ),
    ]
