# Generated by Django 3.1.4 on 2020-12-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201218_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.TextField(default='no department provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.TextField(default='no team provided', max_length=255),
        ),
    ]
