# Generated by Django 3.1.4 on 2020-12-12 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_principle_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('H', 'Happy'), ('S', 'Sad'), ('M', 'Mad'), ('C', 'Chill'), ('SF', "Don't Know")], default='C', max_length=2)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principle', to='human_principle_backend.member')),
            ],
        ),
    ]
