# Generated by Django 3.1.4 on 2020-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_principle_backend', '0002_principle'),
    ]

    operations = [
        migrations.AddField(
            model_name='principle',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
