# Generated by Django 3.1.4 on 2020-12-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_principle_backend', '0003_principle_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principle',
            name='feeling',
        ),
        migrations.AddField(
            model_name='principle',
            name='question_one',
            field=models.CharField(choices=[('1', '6'), ('2', '5'), ('3', '4'), ('4', '3'), ('5', '2'), ('6', '1')], default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='principle',
            name='question_two',
            field=models.CharField(choices=[('1', '6'), ('2', '5'), ('3', '4'), ('4', '3'), ('5', '2'), ('6', '1')], default='4', max_length=2),
        ),
    ]
