# Generated by Django 3.1.4 on 2020-12-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_principle_backend', '0005_auto_20201213_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principle',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='principle',
            name='question_five',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='principle',
            name='question_four',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='principle',
            name='question_seven',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='principle',
            name='question_six',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='principle',
            name='question_three',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4, max_length=1),
        ),
        migrations.AddField(
            model_name='principle',
            name='questionnare_type',
            field=models.CharField(choices=[('Mental', 'Mental'), ('Physical', 'Physical'), ('Emotional', 'Emotional')], default='Mental', max_length=10),
        ),
        migrations.AlterField(
            model_name='principle',
            name='question_one',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='principle',
            name='question_two',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=4, max_length=1),
        ),
    ]
