# Generated by Django 3.1.4 on 2020-12-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_principle_backend', '0012_auto_20201215_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principle',
            old_name='email',
            new_name='username',
        ),
    ]
