# Generated by Django 3.1.4 on 2020-12-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_principle_backend', '0014_auto_20201215_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
