# Generated by Django 3.1.4 on 2020-12-16 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_principle_backend', '0015_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to=settings.AUTH_USER_MODEL),
        ),
    ]
