# Generated by Django 3.1.4 on 2020-12-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_principle_backend', '0016_auto_20201216_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principle',
            old_name='email',
            new_name='user',
        ),
    ]
